### ISSUE TITLE
What is beir?

### ISSUE THREAD

**Issue by yhcc** [quchangle1/COLT#1]
In the train_sbert.py file, it imports a beir package.

**Comment by quchangle1** [comment]
Thank you for your interest in our work. BEIR is a widely used information retrieval framework. You can find the BEIR code repository at this link: https://github.com/beir-cellar/beir. Additionally, you can learn more about it from the BEIR paper available here: https://arxiv.org/abs/2104.08663. These resources should provide you with more detailed information.
