### ISSUE TITLE
一个query对应多个tool的情况下是否有可能会被sentencetransformer误采样

### ISSUE THREAD

**Issue by yhcc** [quchangle1/COLT#2]
由于训练的时候是通过in batch negative sampling的方式采样负例，是否可能导致同一个query的不同tool之间互相成为了负例。例如query1对应了tool1、2、3，是否query1和tool1做匹配例子的时候，恰好query1+tool2、query1+tool2成为了负例。

**Comment by quchangle1** [comment]
感谢您对我们工作的关注，采用Inbatch这种方式进行负采样确实可能会出现这个问题，后续也提出了很多更有效的负采样方法，例如使用Mined Hard Negatives等，您可以在beir框架中找到相关实现的代码~ 希望这些信息对您有所帮助，如果有进一步的问题，欢迎随时交流！
