### ISSUE TITLE
What does the split "tune" mean? The same as "dev" split?

### ISSUE THREAD

**Issue by fairyshine** [quchangle1/COLT#3]
RT, I found query_tool_tune.txt in Datasets/ToolLens/

**Comment by quchangle1** [comment]
Yes, the ‘tune’ split refers to the validation set. However, in our work, the validation set and the test set use the same data.

**Comment by fairyshine** [comment]
> Yes, the ‘tune’ split refers to the validation set. However, in our work, the validation set and the test set use the same data.

Let me see, "test" is a part of "tune". And you only use the "test" split, right?

**Comment by quchangle1** [comment]
Sorry for any confusion. The 'tune' split is indeed the same as the 'dev' split, often used for validation purposes. In our case, we use the same data for both the validation (tune/dev) and test splits. So, the 'test' set is not a part of the 'tune' set, but rather, they are separate splits that happen to share the same data in our setup. We only use this shared data once, treating it as both our validation and test set

**Comment by fairyshine** [comment]
> Sorry for any confusion. The 'tune' split is indeed the same as the 'dev' split, often used for validation purposes. In our case, we use the same data for both the validation (tune/dev) and test splits. So, the 'test' set is not a part of the 'tune' set, but rather, they are separate splits that happen to share the same data in our setup. We only use this shared data once, treating it as both our validation and test set

I find the scale of split "tune" much larger than "test". So which one do you actually use for eval, "tune" or "test"?

**Comment by quchangle1** [comment]
Thank you very much for pointing out this issue! I just discovered that an error occurred during the last file update, which caused a portion of the files to be incorrectly updated. The issue has now been fixed, and the data should be correct.

**Comment by fairyshine** [comment]
Alright ,I got it. Nice work!
