### ISSUE TITLE
如何做推理的

### ISSUE THREAD

**Issue by lgxbil** [quchangle1/COLT#4]
请问在推理阶段，如何处理冷启动问题？一个新的问题，如何进行检索呢？

**Comment by KID-22** [comment]
inference阶段query侧用的还是semantic embedding，tool侧用的是经过semantic learning和collaborative learning后学到的更好的embedding

**Comment by lgxbil** [comment]
论文里好像没说inference，看了一眼代码感觉是这样，请教确认一下。感谢解答
