### ISSUE TITLE
What is the different of the datasets

### ISSUE THREAD

**Issue by ShiJiawenwen** [quchangle1/COLT#5]
Hello, thanks for your work, it is really important!  I would greatly appreciate it if you could tell me the differences between ToolLens, ToolBenchG2, and ToolBenchG3. I look forward to your reply.

**Comment by quchangle1** [comment]
Thank you for your interest in our work! ToolBench is a benchmark commonly used to evaluate the capability of large language models in tool usage. It includes three subsets: ToolBenchG2 generates queries by selecting tools within the same category, while ToolBenchG3 forms queries by selecting tools from a wider range. For more details, you can refer to the original paper: https://arxiv.org/abs/2307.16789.

Regarding the differences between ToolLens and ToolBench, the queries in ToolBench are verbose and semantically direct, whereas ToolLens features concise yet intentionally multifaceted queries that better mimic real-world user interactions. You can find more specifics in the "Datasets" section of our paper.

**Comment by ShiJiawenwen** [comment]
Thanks very much. Are the datasets in your repo the same as the original ToolBench, or do you do the same optimization in queries in your work?

**Comment by quchangle1** [comment]
The queries in the ToolBench dataset in our repo are the same as those in the original dataset, and we only performed data filtering in our work.

**Comment by ShiJiawenwen** [comment]
OK, thanks very much~

**Comment by ShiJiawenwen** [comment]
Hello, I have one more question. As the description  "ToolLens dataset includes 18,770 queries and 464 tools, with each query being associated with 1 ∼ 3 verified tools." in the paper, I want to know is a query need 1~3 tools to solve, or can be solve by these annotated tools separately.

**Comment by quchangle1** [comment]
Apologies for any confusion caused. What I meant to convey is that a query requires the simultaneous use of these tools to be answered, rather than each tool being able to solve the query independently. Thank you for your question!

**Comment by ShiJiawenwen** [comment]
I get. Thanks very much.
